# Generated by Django 3.2.16 on 2022-11-27 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(default='Default name', max_length=200)),
                ('state', models.CharField(default='Central', max_length=30)),
                ('brief_intro', models.TextField(default='Brief introduction of the job post', max_length=500)),
                ('body', models.TextField(blank=True, default='Information of the job post', max_length=500, null=True)),
                ('notification_date', models.DateField(blank=True, null=True)),
                ('online_application_date', models.DateField(blank=True, null=True)),
                ('application_expiry_date', models.DateTimeField(blank=True, null=True)),
                ('application_mode', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], max_length=30)),
                ('application_link', models.URLField(blank=True, null=True)),
                ('minimum_age', models.PositiveIntegerField(default=18, validators=[django.core.validators.MinValueValidator(17), django.core.validators.MaxValueValidator(30)])),
                ('maximum_age', models.PositiveIntegerField(default=28, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(60)])),
                ('minimum_qualification', models.CharField(choices=[('MATRIC', 'Matriculation'), ('INTERMEDIATE', 'Intermediate'), ('GRADUATION', 'Graduate/Bachelors'), ('POST-GRADUATION', 'Post-graduate/Masters'), ('DOCTORATE', 'Ph.D/Doctorate')], max_length=50)),
                ('dept_of_ministry', models.CharField(blank=True, max_length=50, null=True)),
                ('total_posts', models.PositiveIntegerField()),
                ('application_fee', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('official_site', models.URLField(blank=True, null=True)),
                ('admit_card_link', models.URLField(blank=True, null=True)),
                ('notification_link', models.URLField(blank=True, null=True)),
                ('isPublished', models.BooleanField(default=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-application_expiry_date'],
            },
        ),
    ]
