# Generated by Django 3.2.16 on 2022-12-10 11:07

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='body',
        ),
        migrations.AddField(
            model_name='job',
            name='content',
            field=tinymce.models.HTMLField(default='<p>This text is supposed to appear in the rich textbox</p>'),
        ),
    ]
