# Generated by Django 3.2.16 on 2022-11-28 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='isPublished',
            field=models.BooleanField(default=False, verbose_name='Published?'),
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.ForeignKey(default='Central', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='jobs', to='jobs.state'),
        ),
    ]
