# Generated by Django 3.2.16 on 2022-12-03 10:01

from django.db import migrations, models
import django.db.models.deletion
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20221202_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.ForeignKey(default=jobs.models.get_default_state, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='jobs', to='jobs.state', to_field='state'),
        ),
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='state_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
