# Generated by Django 3.2.16 on 2022-12-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20221214_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured job?'),
        ),
        migrations.AddField(
            model_name='job',
            name='result_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='syllabus_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
