# Generated by Django 3.2.16 on 2022-12-03 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20221203_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='jobs.state'),
        ),
    ]
