# Generated by Django 3.2.16 on 2023-01-04 15:00

import django.core.validators
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_name', models.CharField(default='Default name', max_length=200)),
                ('admission_started_on', models.DateField(blank=True, null=True)),
                ('brief_intro', models.TextField(default='Brief introduction of the admission to the course', max_length=500)),
                ('application_fees', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3000)])),
                ('course_name', models.CharField(default='Default name', max_length=200)),
                ('eligibility', models.CharField(choices=[('MATRIC', 'Matriculation'), ('INTERMEDIATE', 'Intermediate'), ('GRADUATION', 'Graduate/Bachelors'), ('POST-GRADUATION', 'Post-graduate/Masters'), ('DOCTORATE', 'Ph.D/Doctorate')], max_length=50)),
                ('instructions', tinymce.models.HTMLField()),
                ('admission_link', models.URLField(blank=True, default='', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='answerkey_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='correction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='fee_last_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='female_fee',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3000)]),
        ),
        migrations.AddField(
            model_name='job',
            name='general_obc_fee',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3000)]),
        ),
        migrations.AddField(
            model_name='job',
            name='sc_st_ph_fee',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3000)]),
        ),
    ]
