# Generated by Django 3.2.16 on 2022-12-03 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0005_alter_job_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='state_code',
        ),
        migrations.AlterField(
            model_name='job',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='jobs', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
