# Generated by Django 3.2.16 on 2023-01-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20230104_2030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admission',
        ),
        migrations.AddField(
            model_name='job',
            name='is_admission',
            field=models.BooleanField(default=False, verbose_name='Is admission?'),
        ),
    ]
