# Generated by Django 3.2.16 on 2022-12-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20221203_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
