# Generated by Django 3.2.16 on 2023-01-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_job_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='keywords',
            field=models.CharField(default='Default name', max_length=200),
        ),
    ]
