# Generated by Django 3.2.16 on 2023-01-16 07:00

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_job_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry', models.CharField(blank=True, max_length=180, null=True)),
                ('slug', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Ministry',
                'verbose_name_plural': 'Ministries',
            },
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_on'], 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.RemoveField(
            model_name='job',
            name='female_fee',
        ),
        migrations.RemoveField(
            model_name='job',
            name='general_obc_fee',
        ),
        migrations.RemoveField(
            model_name='job',
            name='sc_st_ph_fee',
        ),
        migrations.AddField(
            model_name='state',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='application_fee',
            field=tinymce.models.HTMLField(default='Not announced'),
        ),
        migrations.AlterField(
            model_name='job',
            name='brief_intro',
            field=models.TextField(default='Brief introduction of the job post', max_length=600),
        ),
        migrations.AddField(
            model_name='job',
            name='ministry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.ministry'),
        ),
    ]
