# Generated by Django 3.2.16 on 2023-01-16 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20230116_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='dept_of_ministry',
        ),
    ]
