# Generated by Django 3.2.16 on 2023-01-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20230119_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
