# Generated by Django 3.2.16 on 2023-01-21 06:24

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_remove_state_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'get_latest_by': 'created_on', 'ordering': ['-created_on'], 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.RemoveField(
            model_name='job',
            name='maximum_age',
        ),
        migrations.RemoveField(
            model_name='job',
            name='minimum_age',
        ),
        migrations.AddField(
            model_name='job',
            name='age',
            field=tinymce.models.HTMLField(default=15),
        ),
        migrations.AlterField(
            model_name='job',
            name='ministry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.ministry'),
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.state'),
        ),
    ]
