# Generated by Django 3.2.16 on 2023-01-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_auto_20230121_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archived?'),
        ),
    ]
