# Generated by Django 3.2.16 on 2023-01-25 17:16

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_job_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='admit_card_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='extra_info_box_1',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='extra_info_box_2',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
