# Generated by Django 3.2.16 on 2023-01-28 15:24

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_rename_online_application_date_job_application_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='brief_intro',
            field=models.TextField(default='Brief introduction of the job post'),
        ),
        migrations.AlterField(
            model_name='job',
            name='important_dates',
            field=tinymce.models.HTMLField(default='\n    <p>Application Begin : <strong>Unannounced</strong></p>\n    <p>Last Date for Apply Online : <strong>Unannounced</strong></p>\n    <p>Pay Exam Fee Last Date : <strong>Unannounced</strong></p>\n    <p>Admit Card Date : <strong>Unannounced</strong></p>\n    <p>Exam Date : <strong>Unannounced</strong></p>\n    '),
        ),
    ]
