# Generated by Django 3.2.16 on 2023-01-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_auto_20230128_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='total_posts',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
