# Generated by Django 3.2.16 on 2023-02-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_alter_job_total_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='advertisement_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='important_links',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='keywords',
            field=models.CharField(default='Default keywords', max_length=200),
        ),
    ]
